name: test

env:
  prodution: '[{ "name": "apple", "quantity": 1 },{ "name": "orange", "quantity": 2 }]'
on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: production
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: |
          echo ${{ env.${{inputs.env}} }}
          echo 'g'
      
      
      
