name: test

env:
  production: '[{ "name": "apple", "quantity": 1 },{ "name": "orange", "quantity": 2 }]'
  production-eu: something.values.yaml
  production-ca: something2.values.yaml
  myenv: production
on:
  push:
    branches:
      - 'main'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: |
        echo "a=valueA" >> $GITHUB_ENV
        echo "b=valueB" >> $GITHUB_ENV
        echo "c=valueC" >> $GITHUB_ENV

    - name: Print environment variables
      run: |
        for i in a b c; do
          echo "${{ env[$i] }}"
        done

    - name: step-1
      run: |
        for i in production-ca production-eu
        do
          echo "${{ env[$i] }}"
          echo 'g'
          done
        

