name: test

env:
  production: '[{ "name": "apple", "quantity": 1 },{ "name": "orange", "quantity": 2 }]'
  production-eu: something.values.yaml
  production-ca: something2.values.yaml
  myenv: production
on:
  push:
    branches:
      - 'main'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: |
          for ii in production production-eu
          do
            echo '${{ env[production] }}'
            echo 'g'
          done

      
      
      
