name: test

env:
  production: '[{ "name": "apple", "quantity": 1 },{ "name": "orange", "quantity": 2 }]'
  production-eu: something.values.yaml
  production-ca: something2.values.yaml
  myenv: production
on:
  push:
    branches:
      - 'main'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: |
        export a=valueA
        export b=valueB
        export c=valueC

    - name: Print environment variables
      run: |
        for i in a b c; do
          echo "${!i}"
        done
        

